services:
  openresty:
    build: .
    command: bash -c "openresty -g 'daemon off;' -c /usr/local/openresty/nginx/conf/nginx.conf"
    volumes:
    - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    - ./utils.lua:/usr/local/openresty/lualib/resty/utils.lua
    - /home/ubuntu/API-Gateway/jwt_public_key.pem:/etc/ssl/certs/jwt_public_key.pem

    ports:
      - "80:80"
    restart: always
