services:
  openresty:
    build: .
    command: bash -c "openresty -g 'daemon off;' -c /usr/local/openresty/nginx/conf/nginx.conf"
    volumes:
    - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    - ./utils.lua:/usr/local/openresty/lualib/resty/utils.lua
    - /etc/ssl/certs/jwt_public_key.pem:/etc/ssl/certs/jwt_public_key.pem
    - /etc/ssl/certs/API_Gateway_cert.crt:/etc/ssl/certs/API_Gateway_cert.crt
    - /etc/ssl/private/API_Gateway_cert_key.key:/etc/ssl/private/API_Gateway_cert_key.key

    ports:
      - "80:80"
      - "443:443"
    restart: always
